services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    volumes:
      - stats-postgres:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stat -d ewm-stats" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    volumes:
      - main-postgres:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U main -d ewm-main" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  users-db:
    image: postgres:16.1
    container_name: postgres-users-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
    volumes:
      - users-postgres:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U users -d users" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  requests-db:
    image: postgres:16.1
    container_name: postgres-requests-db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=requests
      - POSTGRES_USER=requests
      - POSTGRES_PASSWORD=requests
    volumes:
      - requests-postgres:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U requests -d requests" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  comments-db:
    image: postgres:16.1
    container_name: postgres-comments-db
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=comments
      - POSTGRES_USER=comments
      - POSTGRES_PASSWORD=comments
    volumes:
      - comments-postgres:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U comments -d comments" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  stats-postgres:
  main-postgres:
  users-postgres:
  requests-postgres:
  comments-postgres:
