server:
  port: 0

logging:
    level:
        org:
            hibernate:
                SQL: WARN
            springframework:
                web: INFO
        ru:
            practicum: DEBUG
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${SPRING_DATASOURCE_PASSWORD:requests}
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/requests}
        username: ${SPRING_DATASOURCE_USERNAME:requests}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                jdbc:
                    batch_size: 10
        show-sql: false

stats:
  service:
    id: stats-server

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
      waitDurationInOpenState: 10000 # 10 секунд в миллисекундах
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
