spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND, INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET, POST, PUT, PATCH

server:
  port: 8080

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    gateway:
      enabled: true
      access: read-only


